// Hello everybody, that's my first amazing program.
//I know there are bugs, I'm sorry.
//That program is a little bit hard(for me.).
//==============================v2.3=============================
//I haven't got much time to finish all description about commands.
//Sorry for some faults about my English, I'm from Turkey and that's what I know. 
//---------------------------CODE BEGINS HERE----------------------------------\\
#include <LiquidCrystal.h> //Adding the library...

LiquidCrystal lcd(12,11,5,4,3,2); //Defining the pins that attached to Arduino's pins...

int temp = 0;//Creating "temp" variable...

const int ledPin_hot = 7;
const int ledPin_cold = 8;
const int sensorPin= A0; //Constants won't change because we use them to define pins...

void setup() {
lcd.begin(16,2); //Our LCD...
lcd.print("Hello World!"); //Printing "Hello World!"...
delay(1000); //Waiting 1 second for stability...
lcd.clear(); //Clearing "Hello World!"...
lcd.print("Cannot calculate"); //Making a warning and printing it... (first)
lcd.setCursor(0,2); //Setting cursor to cooordinates(0,2)...
lcd.print("under 0"); //Making a warning and printing it... (second)
delay(2000); //Waiting 2 seconds for stability...
lcd.clear(); //Clearing all written...
lcd.print("If hot, red");
delay(1500); //Waiting 1.5 seconds for stability...
lcd.clear(); //Clearing all written...
lcd.print("If cold blue");
delay(1500);  //Waiting 1.5 seconds for stability...
lcd.clear(); //Clearing all written...
}

void loop() {
lcd.clear(); //Starts with clearing...
temp = analogRead(sensorPin); //Reads "sensorPin" and gets the value, The "temp" variable equals to value now...
temp = temp * 0.48828125; //Recalculates temp, the number "0.48828125" is not a variable, but it is calculated for 5V in... 
temp = temp + 1; //There is a bug and we must use this...{for example: the real temp. is 25, but the termometer shows 24...}
lcd.print("Temp is: "); //Finally
lcd.print(temp);  //It prints
lcd.print("'C"); //The real temp. ...

  if (temp > 40) {
    digitalWrite(ledPin_hot, HIGH);
    delay(10000);
    digitalWrite(ledPin_hot, LOW);
  }

  if (temp < 10) {
    digitalWrite(ledPin_cold, HIGH);
    delay(10000);
    digitalWrite(ledPin_cold, LOW);
  }
delay(1000); // Waits 1 seconds for stability...
}
